### ISSUE TITLE
Errors in console

### ISSUE THREAD

**Issue by renkun-ken** [REditorSupport/vscode-R#1033]
Currently, the following errors appear quite often in the console:

```
ERR Cannot read property 'globalenv' of undefined: TypeError: Cannot read property 'globalenv' of undefined
```

```
ERR Bad progress location: rHelpPages
```

It seems that they are caused by that we don't properly check if `globalenv` is available on hover and completion, and `rHelpPages` viewer not created when `doWithProgress` is called.
